#ifndef AsrItemH
#define AsrItemH

#define MIC_VOL 0x45	//麦克风增益   影响识别效果
#define SPEAKER_VOL 0x1//扬声器音量

#define ITEM_COUNT 17 //识别语句数量

#define STR_00 "ni hao"
#define STR_01 "hong se"
#define STR_02 "lan se"
#define STR_03 "lv se"
#define STR_04 "kai men"
#define STR_05 "ping guo"
#define STR_06 "wo hen fan"
#define STR_07 "ting ge"
#define STR_08 "liao tian"
#define STR_09 "shi xin zai gan sa"
#define STR_10 "wei sa"
#define STR_11 "zai xiang shui"
#define STR_12 "ni ji sui le"
#define STR_13 "ni de sheng ri"
#define STR_14 "lv se"
#define STR_15 "lan se"
#define STR_16 "hong se"
#define STR_17 ""
#define STR_18 ""
#define STR_19 ""
#define STR_20 ""
#define STR_21 ""
#define STR_22 ""
#define STR_23 ""
#define STR_24 ""
#define STR_25 ""
#define STR_26 ""
#define STR_27 ""
#define STR_28 ""
#define STR_29 ""
#define STR_30 ""
#define STR_31 ""
#define STR_32 ""
#define STR_33 ""
#define STR_34 ""
#define STR_35 ""
#define STR_36 ""
#define STR_37 ""
#define STR_38 ""
#define STR_39 ""
#define STR_40 ""
#define STR_41 ""
#define STR_42 ""
#define STR_43 ""
#define STR_44 ""
#define STR_45 ""
#define STR_46 ""
#define STR_47 ""
#define STR_48 ""
#define STR_49 ""

#endif
